config/routes.rb
Rails.application.routes.draw do
  root 'users#activate'
  resources :users, only: [:index,:new,:create] do
  end
  post '/mailgun/webhooks', :to => 'mailgun#webhook_stats'
end

app/models/user.rb
class User < ActiveRecord::Base

	EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

	validates :email_id, format: {with: EMAIL_FORMAT, message: "invalid email id"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mailgun_controller.rb
class MailgunController < ApplicationController

	def webhook_stats
		user = User.find_by_email_id(params.require(:recipient))
		email = EmailService.new(user).past_emails(params.require(:tag))
		subject = email.present? ? email['headers']['subject']:""
		Csv::CsvHandler.new("tmp/","webhook_data.csv").write_to_file([params.require(:ip),params[:recipient],subject,params.require(:event)])
		head :ok
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def activate
		render text: "Thank you for activating your account"
	end

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.create(params[:user].permit(:name,:email_id))
		if @user.errors.any?
			render :new
		else
			redirect_url = "#{request.protocol}#{request.host_with_port}#{request.fullpath}"
			EmailService.new(@user).send_activation_email(redirect_url)
			EmailService.new(@user).send_reminder_mail
			# ActivationEmailReminderWorker.perform_in(15.seconds.from_now,@user.id)
			redirect_to users_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_content_helper.rb
module EmailContentHelper

  SUPPRESSIONS = {
    :BOUNCE => 'bounces',
    :UNSUBSCRIBE => 'unsubscribes',
    :COMPLAINT => 'complaints'
  }

	TAGS = {
	  :ACTIVATION => 'activation'
	}

  EVENT_TYPES = {
    :OPENED => 'opened',
    :ACCEPTED => 'accepted'
  }

	SUBJECTS = {
	  :ACTIVATION => 'Activate your account',
    :ACTIVATION_REMINDER => 'Waiting to hear from you'
	}

	MESSAGES = {
    :ACTIVATION => 'Welcome %s, Please activate your account by clicking on %s',
    :ACTIVATION_REMINDER => " %s, We still haven't seen your account activated"
  }

  def self.getSubject(action, subject_vars)
  	if subject_vars.present?
    	return SUBJECTS[action] % subject_vars
    end
    return SUBJECTS[action]
  end

  def self.getMessage(action, text_vars)
  	if text_vars.present?
  	 return MESSAGES[action] % text_vars
  	end
  	return MESSAGES[action]
  end

  def self.getTags(tag)
  	return TAGS[tag]
  end

  def self.getSuppressionType(type)
    return SUPPRESSIONS[type]
  end

  def self.getEventType(type)
    return EVENT_TYPES[type]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailSoup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_errors_message.html.erb
<% if object.errors.any? %>
    <% object.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= user.name %>
    <%= user.email_id %>
    </br>
<%end%>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= form_for @user, url: users_path do |f| %>
 <%= render 'shared/errors_message', :object => @user %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email_id %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>